weather/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.weather_list, name="weather_list"),
    path('create/', views.city_create, name="city_create"),
    path('<slug>/',views.weather_detail, name="weather_detail"),
    path('<slug>/delete/', views.city_delete, name="city_delete"),
    path('<slug>/edit/', views.city_edit, name='city_edit'),
]

weather_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

class City(models.Model):
    class Meta:
        verbose_name_plural = "cities"
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    rus_name = models.CharField(max_length=100, blank=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('weather:weather_detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(City, self).save(*args, **kwargs)

weather/forms.py
from django import forms
from .models import City
from django.core.exceptions import ValidationError

class CityForm(forms.ModelForm):
    name = forms.CharField(label="Название города", max_length=100, widget=forms.TextInput(attrs={"size":36,"placeholder":"Введите название города по-английски", "autocomplete" : "off"}))
    #slug = forms.CharField(label="Friendly URL", required=False, widget=forms.TextInput(attrs={"size":36,"placeholder":"Введите friendly url для этого города", "autocomplete" : "off"}))
    rus_name = forms.CharField(label="Русское название",required=False, widget=forms.TextInput(attrs={"size":36,"placeholder":"Введите название этого города по-русски", "autocomplete" : "off"}))
    class Meta:
        model = City
        fields = ['name', 'rus_name']# 'slug', ]

weather/views.py
from django.http import Http404
import requests
from django.shortcuts import render, redirect, get_object_or_404
from .models import City
from .forms import CityForm
from django.utils.text import slugify
import random, string

# Create your views here.

def weather_list(request):
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&lang=ru&appid=be11199a30cca179654909b1d5c364a8'

    city_weather_data = []
    cities = City.objects.all()
    for city in cities:
        res = requests.get(url.format(city)).json()
        if res['cod'] == "404":
            city.delete()
        else:
            city_weather = {
                'slug': city.slug,
                'name': res['name'],
                'rus_name': city.rus_name,
                'temperature': res['main']['temp'],
                'pressure': res['main']['pressure'],
                'condition': res['weather'][0]['description'],
                'temp_min':res['main']['temp_min'],
                'temp_max':res['main']['temp_max'],
                'icon': res['weather'][0]['icon'],
                'wind': res['wind']['speed'],
                'humidity':res['main']['humidity'],
            }
            city_weather_data.append(city_weather)
    if len(city_weather_data) <= 5:
        context = {'city_weather_data': city_weather_data}
        return render(request, 'weather/weather_list.html', context)
    elif len(city_weather_data) > 5:
        list_length = len(city_weather_data) - 5
        for i in range(list_length):
            del city_weather_data[-1]
        context = {'city_weather_data': city_weather_data}
        return render(request, 'weather/weather_list.html', context)

def weather_detail(request, slug=None):
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&lang=ru&appid=be11199a30cca179654909b1d5c364a8'

    city = get_object_or_404(City, slug=slug)

    res = requests.get(url.format(city)).json()
    if res['cod'] == "404":
        return redirect('weather:weather_list')
    else:
        city_weather_data = {
            'slug': city.slug,
            'name': res['name'],
            'rus_name': city.rus_name,
            'temperature': res['main']['temp'],
            'condition': res['weather'][0]['description'],
            'temp_min':res['main']['temp_min'],
            'temp_max':res['main']['temp_max'],
            'icon': res['weather'][0]['icon'],
            'wind': res['wind']['speed'],
            'humidity':res['main']['humidity'],
        }
    context = {'city_weather_data':city_weather_data}
    return render(request, 'weather/weather_detail.html', context)


def city_delete(request, slug=None):
    city = get_object_or_404(City, slug=slug)
    city.delete()
    return redirect('weather:weather_list')

def city_create(request):
    queryset = City.objects.all()
    if request.method == "POST":
        form = CityForm(request.POST or None)
        if form.is_valid():
            city = form.save(commit=False)
            curr_city = City.objects.filter(slug__icontains=slugify(city.name))
            if curr_city.exists():
                city.slug=slugify(city.name)+"-"+str(random.randint(1000,10000))+str(''.join(random.choice(string.ascii_lowercase) for i in range(6)))
                city.save()
            else:
                city.save()
            return redirect(city.get_absolute_url())
    else:
        form = CityForm()
        context = {'form' : form}
    return render(request, 'weather/city_create.html', context)

def city_edit(request, slug=None):
    queryset = City.objects.all()
    city = get_object_or_404(City, slug=slug)
    if request.method == "POST":
        form = CityForm(request.POST or None, instance=city)
        if form.is_valid():
            city = form.save(commit=False)
            curr_city = City.objects.filter(slug__icontains=slugify(city.name))
            if curr_city.exists():
                city.slug=slugify(city.name)+"-"+str(random.randint(1000,10000))+str(''.join(random.choice(string.ascii_lowercase) for i in range(6)))
                city.save()
            else:
                city.slug=slugify(city.name)
                city.save()
            return redirect(city.get_absolute_url())
    else:
        form = CityForm(instance=city)
        context = {'form' : form}
    return render(request, 'weather/city_edit.html', context)

templates/weather/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="icon" type="image/gif" href="static/images/weather_icon.png"/>
  </head>
  <body>

    <div class="navbar">
      <a href="/" class="headline">Прогноз погоды</a>
      <p><span id="demo"></span>, <span id="datetime"></span> <span id="year"></span>, <span id="time"></span></p>
    </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <script src="/static/js/script.js"></script>

  </body>
</html>

templates/weather/city_create.html
{% extends "weather/base.html" %}
{% block title %}Добавить{% endblock %}
{% block content %}
  <form method="POST">
    <h4 style="margin-left:-20px;">Добавить город</h4>
    <div class="city-form">
      <p class="comments-1">прим. barcelona</p>
      {% csrf_token %}
      {{form.as_p }}
      <p class="comments-2">прим. Барселона</p>
      <input type="submit" class="btn btn-success" value="Create post">
    </div>
  </form>

{% endblock %}

templates/weather/city_edit.html
{% extends "weather/base.html" %}
{% block title %}Изменить{% endblock %}
{% block content %}
  <form method="POST">
    <h4 style="margin-left:-20px;">Изменить город</h4>
    <div class="city-form">
      <p class="comments-1">прим. barcelona</p>
      {% csrf_token %}
      {{form.as_p }}
      <p class="comments-2">прим. Барселона</p>
      <input type="submit" class="btn btn-success" value="Create post">
    </div>
  </form>

{% endblock %}

templates/weather/weather_detail.html
{% extends "weather/base.html" %}

{% block title %}
  {% if city_weather_data.rus_name %}
    {{city_weather_data.rus_name|capfirst}}
  {% else %}
    {{city_weather_data.name|capfirst}}
  {% endif %}
{% endblock %}


{% block content %}
  {% if city_weather_data.rus_name %}
    <h3 style="display:inline;">{{city_weather_data.rus_name|capfirst}}</h3>
  {% else %}
    <h3 style="display:inline;">{{city_weather_data.name|capfirst}}</h3>
  {% endif %}
  <a class="change-delete" href="{% url 'weather:city_edit' slug=city_weather_data.slug %}">Изменить</a>
  <a class="change-delete" href="{% url 'weather:city_delete' slug=city_weather_data.slug %}" style="color:red;">Удалить</a>
  <div class="icon-detail">
    <img src="http://openweathermap.org/img/w/{{city_weather_data.icon}}.png" alt="weather-icon">
  </div>
  <br>
  <p style="font-size:33px;">{{city_weather_data.temperature}} °C</p>
  <p>{{city_weather_data.condition|capfirst}}</p>
  <div class="info-detail">
    <p>Ветер: <small class="custom-string">{{city_weather_data.wind}} м/c</small></p>
    <p>Влажность: <small class="custom-string">{{city_weather_data.humidity}}%</small></p>
    <p>Минимальная температура: <small class="custom-string">{{city_weather_data.temp_min}} °C</small></p>
    <p>Максимальная температура: <small class="custom-string">{{city_weather_data.temp_max}} °C</small></p>
  </div>
{% endblock %}

templates/weather/weather_list.html
{% extends "weather/base.html" %}
{% block title %}Прогноз погоды{% endblock %}
{% block content %}
    {% for city in city_weather_data %}
      {% if forloop.first %}
        <div class="background">
          <div class="main-div">
            <div class="head-div">
              <a href="{% url 'weather:city_delete' slug=city.slug %}" class="head-name"><i class="fas fa-times"></i></a>
              {% if city.rus_name %}
                <a href="{% url 'weather:weather_detail' slug=city.slug %}" class="head-name">{{city.rus_name|capfirst}}</a>
              {% else %}
                <a href="{% url 'weather:weather_detail' slug=city.slug %}" class="head-name">{{city.name|capfirst}}</a>
              {% endif %}
            </div>
            <figure class="icon-box-1">
              <img src="http://openweathermap.org/img/w/{{city.icon}}.png" alt="weather-icon">
            </figure>
            <div class="main-temperature">
              {% if city.temperature > 0 %}
                <p>+{{city.temperature}}°C</p>
              {% elif city.temperature < 0 %}
                <p>{{city.temperature}}°C</p>
              {% elif city.temperature == 0 %}
                <p>{{city.temperature}}°C</p>
              {% endif %}
            </div>
            <div class="vl"></div>
            <div class="main-left-side">
              <p><small style="font-size:20px;" class="custom-string">{{city.condition|capfirst}}</small></p>
              <p>Ветер: <small class="custom-string">{{city.wind}} м/c</small></p>
              <p>Влажность: <small class="custom-string">{{city.humidity}}%</small></p>
            </div>
            <div class="main-right-side">
              <p>Минимальная температура: <small class="custom-string">{{city.temp_min}} °C</small></p>
              <p>Максимальная температура: <small class="custom-string">{{city.temp_max}} °C</small></p>
            </div>
          </div>
        </div>
      {% else %}
        <div class="other-cities">
          <a href="{% url 'weather:city_delete' slug=city.slug %}"><i class="fas fa-times"></i></a>
          <div class="icon-box-2">
            <img src="http://openweathermap.org/img/w/{{city.icon}}.png" alt="weather-icon">
          </div>
          <div class="info-box">
            {% if city.rus_name %}
              <a href="{% url 'weather:weather_detail' slug=city.slug %}">{{city.rus_name|capfirst}}</a>
            {% else %}
              <a href="{% url 'weather:weather_detail' slug=city.slug %}">{{city.name|capfirst}}</a>
            {% endif %}
            {% if city.temperature >= 0 %}
              <p class="custom-string"style="margin-top:17px;">+{{city.temperature}} °C</p>
            {% else %}
              <p class="custom-string"style="margin-top:17px;">{{city.temperature}} °C</p>
            {% endif %}
            <p style="font-size:19px;color:black;margin-bottom:5px;">{{city.condition|capfirst}}</p>
          </div>
        </div>
      {% endif %}
    {% endfor %}
    {% if city_weather_data|length < 5 %}
      <div class="other-cities">
        <div class="add-new-cities">
          <a href="{% url 'weather:city_create' %}" style="text-decoration:none;"><i class="far fa-plus-square"></i> <h4 style="display:inline;">Добавить город</h4></a>
        </div>
      </div>
    {% endif %}
{% endblock %}